debug: false

spring.jpa.show-sql: true
spring.jpa.generate-ddl: false

com.sap.icd.odatav2.spring:
   servicePath: leaveapp
   persistenceUnit: leaveappdb
   language: en
   country: US
management:
  context-path: /admin
  security:
    enabled: false
---
spring:
    h2:
      console:
        enabled: true
        path: /console
    profiles: default
    datasource:
      username: sa
      password:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:~/leaveapprovaldb;DB_CLOSE_ON_EXIT=FALSE
      
RRMEXEC_STORE_URL: http://localhost:8095/rrm/routeupdate
